print(sum(c.isupper() for line in open('content.txt') for c in line))
print("----------------------------------------")
print(open('inheritance.py').read())
print("----------------------------------------")
print(open('date-day.py').read(50))
print("----------------------------------------")
print('\n--- '.join(line[:10] for line in open('date-day.py')))
print("----------------------------------------")
print(sum(1 for _ in open('senyorcitizen.py')))
